# .rubocop.yml

require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

# .rubocop.yml

Metrics/AbcSize:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Lint/Void:
  Enabled: false

Lint/Syntax:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
